dist: xenial
sudo: required
git:
  depth: 3

addons:
  apt:
    update:
    - true
before_script:
  - sudo apt-get install openjdk-8-jre openjdk-8-jdk
  - cd $HOME && sudo apt-get install git axel -y && git clone https://github.com/ALGPHELLO/scripts.git && cd scripts && sudo bash setup/android_build_env.sh && sudo bash setup/install_android_sdk.bash
  - cd $HOME && mkdir omni
  - cd omni
  - repo init -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.0 --depth=1
  - repo sync --force-sync -j32
script:
  - cd $HOME/omni && git clone https://github.com/ALGPHELLO/android_device_honor_AUM-TWRP.git -b oreo-8.0 device/honor/AUM --depth=1
  - rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery.git -b android-8.0 bootable/recovery --depth=1
  - git clone https://github.com/TeamWin/android_device_qcom_common.git -b android-8.0 device/qcom/common --depth=1
  - source build/envsetup.sh
  - lunch omni_AUM-userdebug
  - export ALLOW_MISSING_DEPENDENCIES=true
  - make -j32 recoveryimage
after_success:
    - cp $HOME/omni/out/target/product/AUM/recovery.img $HOME/omni/TWRP-AUM_L29-$(date +"%Y%m%d").img
  

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_TB"
  file_glob: true
  file: $HOME/omni/*.img
  on:
    tags: false
    repo: ALGPHELLO/android_device_honor_AUM-TWRP
    branch: oreo
branches:
  except:
    - /^(?i:untagged)-.*$/
